### ISSUE TITLE
Custom annotation (rectangle) style

### ISSUE THREAD

**Issue by simon-bre** [Kunduin/react-picture-annotation#51]
Hi,

first of all, thanks for this great component, does everything one expects.

There's just one thing I couldn't figure out yet: is there a way to change the style of the annotation marks, i.e. the rectangles? If not, is there a chance this will be implemented in the future?

In particular I would find it useful to keep the fill of the rectangle fully transparent when selected, as the semi-transparent overlay could introduce a bias in some usecases..

Cheers,
Simon

**Comment by Kunduin** [comment]
Hi Simon!

Sorry for my negligence, you can only fork this project to change the style.
I will finish this feature, but I am not sure when to finish it because I am busy recently.

I found another great project about annotation [react-image-annotation](https://github.com/Secretmapper/react-image-annotation). If you have urgent needs, maybe you can check it out.

Thanks,
Bay

**Comment by Kunduin** [comment]
Hi Simon! I finally completed this feature, hahaha

**Comment by dipeshparashar** [comment]
@Kunduin Is it possible to automatically trigger the selection of just drawn annotation ? So the user does not have manually do that task.
